### DISCUSSION TITLE
0.0.17

### DISCUSSION THREAD

**Discussion by harshdoesdev** [shuru-project/shuru#13] [Announcements]
# Release Notes for Shuru v0.0.17

We are excited to announce the release of Shuru v0.0.17! This update introduces a new, more streamlined syntax for defining tasks in the `shuru.toml` configuration file, enhancing readability and ease of use.

### New Syntax

The new syntax for defining tasks is now organized under the [tasks] section, allowing for a clearer structure:

```toml
[versions]
node = "v16.14.0"
python = "3.9.9"

[tasks.setup]
command = '''
npm install
pip3 install -r requirements.txt
'''

[tasks.frontend-dev]
command = "npm run dev"

[tasks.backend-dev]
command = "python3 app.py"

[tasks.build]
command = "npm run build"
```

### Old Syntax

Previously, tasks were defined using an array format with [[task]], which has now been replaced by the more organized section-based format:

```toml
[versions]
node = "v16.14.0"
python = "3.9.9"

[[task]]
name = "setup"
command = '''
npm install
pip3 install -r requirements.txt
'''

[[task]]
name = "frontend-dev"
command = "npm run dev"

[[task]]
name = "backend-dev"
command = "python3 app.py"

[[task]]
name = "build"
command = "npm run build"
```

### Benefits of the New Syntax

- Improved Clarity: The new format clearly distinguishes between tasks, making it easier to read and maintain.
- Consistency: The new structure aligns with other common configuration styles, facilitating easier adoption for new users.

We encourage all users to update their shuru.toml files to the new syntax to take advantage of these improvements. Thank you for your continued support, and we look forward to your feedback!

**Full Changelog**: https://github.com/shuru-project/shuru/compare/0.0.16...0.0.17

<hr /><em>This discussion was created from the release <a href='https://github.com/shuru-project/shuru/releases/tag/0.0.17'>0.0.17</a>.</em>
